# Debugging Loader for Netplay VOOT Extensions
#
# $Id: Makefile,v 1.1 2002/06/11 22:25:28 quad Exp $

LOADER_WORK = ../common
LOADER_TARGET = debug
LOADER_OBJS = debug.o gdrom.o boot.o
LOADER_LIBS = -lconio
LOADER_DEFS = -DDEBUG=1

include ../common/Makefile.loader
