# Debugging Loader for Netplay VOOT Extensions
#
# $Id: Makefile,v 1.2 2002/11/07 02:16:01 quad Exp $

LOADER_WORK = ../common
LOADER_TARGET = debug
LOADER_OBJS = debug.o gdrom.o
LOADER_LIBS = -lconio
LOADER_DEFS = -DDEBUG=1

include ../common/Makefile.loader
