# Grapical Loader for Netplay VOOT Extensions
#
# $Id: Makefile,v 1.1 2002/06/05 04:42:07 quad Exp $

LOADER_WORK = ../common
LOADER_TARGET = graphic
LOADER_OBJS = main.o anim.o gdrom.o boot.o
LOADER_LIBS = -lgl -lpng -lz -ldcutils -lm
LOADER_FILES = netplay.png

include ../common/Makefile.loader
