# Grapical Loader for Netplay VOOT Extensions
#
# $Id: Makefile,v 1.2 2002/11/07 02:16:02 quad Exp $

LOADER_WORK = ../common
LOADER_TARGET = graphic
LOADER_OBJS = main.o anim.o gdrom.o
LOADER_LIBS = -lgl -lpng -lz -lm
LOADER_FILES = netplay.png

include ../common/Makefile.loader
