DCBASE=/home/scott/dcdev

TARGET=sh-elf
CC=$(DCBASE)/bin/$(TARGET)-gcc -ml -Os -m4-single-only -Wall
LD=$(DCBASE)/bin/$(TARGET)-ld
AS=$(DCBASE)/bin/$(TARGET)-as
AR=$(DCBASE)/bin/$(TARGET)-ar
OBJCOPY=$(DCBASE)/bin/$(TARGET)-objcopy
