# This should be set to your SH4 gcc/libc target base directory
DCBASE=/home/scott/dcdev

# GCC for SH4 configuration
TARGET=sh-elf

CC=$(DCBASE)/bin/$(TARGET)-gcc -ml -m4-single-only -Os -Wall
LD=$(DCBASE)/bin/$(TARGET)-ld
AS=$(DCBASE)/bin/$(TARGET)-as
AR=$(DCBASE)/bin/$(TARGET)-ar
OBJCOPY=$(DCBASE)/bin/$(TARGET)-objcopy
