#
# Top-level common variables for making the Netplay VOOT Extensions
#  distribution.
#
# $Id: Makefile.config,v 1.1 2002/06/12 00:31:27 quad Exp $

NP_BASE=/home/scott/Projects/VOOT/prog/np-voot
DC_BASE=/home/scott/dcdev

LIBDREAM_BASE = $(NP_BASE)/../libdream
KOS_BASE = $(NP_BASE)/../kos-cvs

# Nothing below this line should ever be modified.

DC_TARGET=sh-elf
DC_CC=$(DC_BASE)/bin/$(DC_TARGET)-gcc -ml -Os -m4-single-only -Wall -D_arch_dreamcast
DC_LD=$(DC_BASE)/bin/$(DC_TARGET)-ld
DC_AS=$(DC_BASE)/bin/$(DC_TARGET)-as
DC_AR=$(DC_BASE)/bin/$(DC_TARGET)-ar
DC_OBJCOPY=$(DC_BASE)/bin/$(DC_TARGET)-objcopy
DC_SIZE=$(DC_BASE)/bin/$(DC_TARGET)-size

PC_CC=gcc -O2 -Wall

CLEAN_OBJS = *.o
CLEAN_BACKUP = *~ DEADJOE
CLEAN_COMMON = $(CLEAN_OBJS) $(CLEAN_BACKUP)

GCC_LIBS = -lgcc
GCC_INCS = -I$(KOS_BASE)/libc/include

KOS_LIBS = -L$(KOS_BASE)/lib -lkallisti $(GCC_LIBS)
KOS_INCS = -I$(KOS_BASE)/include -I$(KOS_BASE)/kernel/arch/dreamcast/include $(GCC_INCS)
KOS_OBJS = $(KOS_BASE)/kernel/arch/dreamcast/kernel/startup.o

KOS_GENROMFS = $(KOS_BASE)/utils/genromfs/genromfs
KOS_BIN2O = $(KOS_BASE)/utils/bin2o/bin2o
